spring:
  datasource:
    url: ${MCD_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${MCD_DB_USERNAME}
    password: ${MCD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL11Dialect
        show-sql: false
